# Assumes RethinkDB is running on the host.
# Set H2IBOT_* to the correct values

services:
  tracker:
    network_mode: host
    build:
      context: ../server
    environment:
      - H2IBOT_GET_URL=http://a:a@192.168.2.228:8080/jsi
      - H2IBOT_POST_URL=http://a:a@192.168.2.228:8080/jsi
    restart: always
    init: true
  bot:
    network_mode: host
    build:
      context: ../irc
    environment:
      - H2IBOT_GET_URL=http://a:a@192.168.2.228:8080/jsi
      - H2IBOT_POST_URL=http://a:a@192.168.2.228:8080/jsi
    restart: always
    init: true
  dashboard:
    network_mode: host
    build:
      context: ../dashboard
    restart: always
    init: true
