# Assumes RethinkDB is running on the host.
# Set H2IBOT_* to the correct values

services:
  initialise:
    network_mode: host
    build:
      context: initialise_db
    restart: on-failure:3
    init: true
  tracker:
    network_mode: host
    build:
      context: ../server
    environment:
      - H2IBOT_GET_URL=http://a:a@192.168.2.228:8080/jsi
      - H2IBOT_POST_URL=http://a:a@192.168.2.228:8080/jsi
      - TRACKER_BASE_URL="https://mnbot.very-good-quality-co.de/"
    restart: always
    init: true
    depends_on:
      initialise:
        condition: service_completed_successfully
  bot:
    network_mode: host
    build:
      context: ../irc
    environment:
      - H2IBOT_GET_URL=http://a:a@192.168.2.228:8080/jsi
      - H2IBOT_POST_URL=http://a:a@192.168.2.228:8080/jsi
    restart: always
    init: true
    depends_on:
      initialise:
        condition: service_completed_successfully
  dashboard:
    network_mode: host
    build:
      context: ../dashboard
    restart: always
    init: true
    depends_on:
      initialise:
        condition: service_completed_successfully
